---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mypodautoscaler
spec:
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - resource: 
        name: CPU
        target:
          averageUtilization: 70%
          type: Utilization
  scaleTargetRef:
    apiVersion: apps/v1
    kind: 
    name:
           