---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mike-autoscaler
spec:
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: mike-resource
        target:
          type: Utilization
          averageUtilization: 70
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mikey-deploy