---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - image: nginx:1.23
      name: mike-pod
      ports:
        - containerPort: 80
          hostPort: 80
          protocol: TCP

