---
apiVersion: v1
kind: Pod
metadata:
  name: mikey-pod11
  labels:
    app: alpine
spec:
  initContainers:
    - image: alpine:3
      name: mikey-init1
      command: 
        - sleep
      args:
        - 30s
    - image: alpine:3
      name: mikey-init2
      command: 
        - sleep
      args:
        - 15s
  containers:
    - image: nginx:1.23
      name: mikey3
      ports:
        - containerPort: 80
          protocol: TCP