---
apiVersion: v1
kind: Pod
metadata:
  name: label-pod1
  labels:
    app: nginx
spec:
  containers:
    - image: nginx:1.23
      name: mikey1
      ports:
        - containerPort: 80
          protocol: TCP
---
apiVersion: v1
kind: Pod
metadata:
  name: label-pod2
  labels:
    app: jenkins
spec:
  containers:
    - image: jenkins/jenkins:2.383
      name: mikey2
      ports:
        - containerPort: 8080
          protocol: TCP
