---
apiVersion: v1
kind: Pod
metadata:
  name: mikey-pod
  labels:
    name: ravi
spec:
  containers:
    - image: nginx:1.23
      name: mikey1
      ports:
        - containerPort: 80
          hostPort: 80
          protocol: TCP
    - image: jenkins/jenkins:2.383
      name: mikey-pod2
      ports:
        - containerPort: 80
          hostPort: 8080
          protocol: TCP