---
apiVersion: v1
kind: Pod
metadata:
  name: mikey-pod1
  labels:
    name: ravi
spec:
  containers:
    - image: nginx:1.23
      name: mikey1
      ports:
        - containerPort: 80
          protocol: TCP
---
apiVersion: v1
kind: Pod
metadata:
  name: mikey-pod2
  labels:
    name: ravi
spec:
  containers:
    - image: nginx:1.23
      name: mikey2
      ports:
        - containerPort: 80
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata: 
  name: mikey-svc
spec:
  selector:
    name: ravi
  ports:
    - name: webport
      port: 35000
      targetport: 80
