---
apiVersion: v1
kind: Pod
metadata:
  name: mikey-pod
  labels: apps
spec:
  containers:
    - image: nginx:1.23
      name: mikey1
      ports:
        - containerPort: 80
          hostPort: 80
          protocol: TCP