---
apiVersion: v1
kind: Pod
metadata:
  name: mikey-pod
  labels:
    name: mikey-app
spec:
  containers:
    - image: alpine:3
      name: mikey-container
      command:
        - sleep
      args:
        - 1d  