---
apiVersion: v1
kind: ReplicationController
metadata:
  name: my-rc2
spec:
  minReadySeconds: 3
  replicas: 6
  selector:
    ver: "1.23"
  template:
    metadata:
      name: mikey-pod6
      labels:
        app: nginx
        ver: "1.23"
    spec:
      containers:
        - image: nginx:1.23
          name: mike1
          ports:
            - containerPort: 80
              protocol: TCP