---
apiVersion: v1
kind: Pod
metadata:
  name: mikey-pod1
  labels:
    name: ravi
spec:
  restartPolicy: Never
  containers:
    - image: alpine:3
      name: mikey1
      command:
        - sleep
        - 2s