---
apiVersion: v1
kind: Pod
metadata:
  name: nodeselector-pod
spec:
  containers:
    - name: mike-cont1
      image: nginx
      ports:
        - containerPort: 80
          protocol: TCP
  nodeSelector:
    kubernetes.io/hostname: ip-10-0-1-69.us-east-2.compute.internal