---
apiVersion: v1
kind: Pod
metadata:
  name: mike-pod1
spec:
  containers:
    - name: mike-cont
      image: nginx
      ports:
        - containerPort: 80
          protocol: TCP
  tolerations:
    - key: mikey
      operator: Equal
      value: "1"