---
apiVersion: v1
kind: Pod
metadata:
  name: mysqlpod
  annotations:
    configmap.reloader.stakater.com/reload: "myconfigdb"
spec:
  containers:
    - name: mysqlcont
      image: mysql:8.0.31-debian
      ports:
        - containerPort: 3306
          protocol: TCP
      env: 
        - name: MYSQL_ROOT_PASSWORD
          value: mikey
        - name: MYSQL_DATABASE
          value: mikeydatabase
        - name: MYSQL_USER
          value: mikey1
        - name: MYSQL_PASSWORD
          value: mikey1
      envFrom:
        - configMapRef:
            name: myconfigdb
