---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mike-sts
spec:
  minReadySeconds: 3
  replicas: 3
  selector:
    matchLabels:
      app: mysql
  serviceName: my-svc
  template: 
    metadata:
      name: mysqlpod1
      labels:
        app: mysql
    spec:
      containers:
        - name: mike-cont
          image: mysql:8.0.31-debian
          ports:
            - containerPort: 3306
              protocol: TCP
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: mikey
            - name: MYSQL_DATABASE
              value: mikeydatabase
            - name: MYSQL_USER
              value: mikey1
            - name: MYSQL_PASSWORD
              value: mikey1
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mypvc1
  volumeClaimTemplates:
    - apiVersion: v1 
      kind: PersistentVolumeClaim
      metadata:
        name: mypvc1
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        selector:
          matchLabels:
            app: mysql
        storageClassName: gp2
