---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mystatefulset
spec:
  minReadySeconds:
  replicas: 5
  selector:
    matchLabels:
      app: mysql
  serviceName: mysqlsvc
  template:
    metadata:
      name: mysql-pod
      labels: 
        app: mysql 
    spec:
      containers:
        - name: mysql-cont
          image: mysql:8.0.31-debian
          ports:
            - containerPort: 3306
              protocol: TCP
          env: 
            - name: MYSQL_ROOT_PASSWORD
              value: mikey
            - name: MYSQL_DATABASE
              value: mikeydatabase
            - name: MYSQL_USER
              value: mikey1
            - name: MYSQL_PASSWORD
              value: mikey1
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mypvc
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: mypvc
      spec:
        accessModes: 
        - ReadWriteOnce
        resources:
          requests: 
            storage: 1Gi
        storageClassName: gp2
