---
apiVersion: v1
kind: Pod
metadata:
  name: mike-pod
  labels:
    app: nginx
spec:
  containers:
    - name: geethu-cont
      image: nginx
      ports:
        - containerPort: 80
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: mike-svc
  annotations:
    kubernetes.io/role/internal-elb: "1"
spec:
  ports:
    - port: 35000
      protocol: TCP
      targetPort: 80
  selector:
    app: nginx
  type: LoadBalancer
        