---
apiVersion: v1
kind: ReplicationController
metadata:
  name: mikey-rc
  labels:
    app: nginx
spec:
  minReadySeconds: 3
  replicas: 5
  selector:
      app: nginx
  template:
    metadata:
      name: mikey-pod
      labels:
        app: nginx
    spec:
      containers:
        - image: nginx:1.23
          name: mikey-1
          ports:
            - containerPort: 80
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: mikey-svc
  labels:
    app: nginx
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - targetPort: 80
      protocol: TCP