---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mikey-rs1
  labels:
    app: jenkins
spec:
  minReadySeconds: 3
  replicas: 12
  selector:
    matchExpressions:
      - key: mikey
        operator: NotIn
        values:
          - rockstar
  template:
    metadata:
      name: mikey-jenkins
      labels:
        app: jenkins
    spec:
      containers:
        - image: jenkins:2.60.3
          name: mikey-containers
          ports:
            - containerPort: 8080
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: mikey-svc2
  labels:
    app: jenkins
spec:
  selector:
    app: jenkins
  type: LoadBalancer
  ports:
    - port: 35000
      targetPort: 8080
      protocol: TCP