---
apiVersion: batch/v1
kind: Job
metadata:
  name: mikey-job
  namespace: mike-namespace
spec:
  backoffLimit: 3
  template:
    metadata:
      name: mikey-pod
      namespace: mike-namespace
    spec:
      restartPolicy: OnFailure
      containers:
        - image: alpine:3
          name: mikey-cont1
          command:
            - sleep
            - 60s