---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc
spec:
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels: 
      app: mysql
  storageClassName: gp2
  volumeName: mysqlpvc-vol
  