---
apiVersion: v1
kind: Pod
metadata:
  name: mysqlpod
spec:
  containers:
    - name: mysqlcont
      image: mysql:8.0.31-debian
      ports:
        - containerPort: 3306
          protocol: TCP
      env: 
        - name: MYSQL_ROOT_PASSWORD
          value: mikey
        - name: MYSQL_DATABASE
          value: mikeydatabase
        - name: MYSQL_USER
          value: mikey1
        - name: MYSQL_PASSWORD
          value: mikey1
      volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-vol
  volumes:
    - name: mysql-vol
      persistentVolumeClaim: 
        claimName: mypvc