---
apiVersion: v1
kind: Pod
metadata:
  name: mikey-pod
  labels: 
    app: mysql
spec:
  containers:
    - image: mysql:8.0.31-debian
      name: mikey-cont1
      ports:
        - containerPort: 3306
          protocol: TCP
      volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysqlpvc-vol
  volumes:
    - name: mysqlpvc-vol
      persistentVolumeClaim: 
        claimName: mypvc
        readOnly: false

      