---
apiVersion: v1
kind: ReplicationController
metadata:
  name: mikey-rc
  labels:
    app: nginx
spec:
  minReadySeconds: 3
  replicas: 5
  selector:
    app: nginx
  template:
    metadata:
      name: mikey-pod
      labels:
        app: nginx
    spec:
      containers:
        - image: nginx:1.23
          name: mikey-container
          ports:
            - containerPort: 80
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: rc-svc
  labels: 
    app: nginx
spec:
  selector:
    app: nginx
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80

  