---
apiVersion: v1
kind: Deployment
metadata:
  name: mikey-db2
  labels: 
    database: mysql
spec:
  minReadySeconds: 3
  replicas: 1
  selector:
    matchLabels:
      database: mysql
  strategy: 
    maxSurge: 25%
    maxUnavailable: 25%
  template:
    metadata:
      labels:
        database: mysql
    spec:
      containers: 
        - image: library/mysql:13-alpine
          name: mysql-db
          ports:
            - containerPort: 3306
              protocol: TCP
              