---
apiVersion: v1
kind: Deployment
metadata:
  name: mikey-db1
  labels: 
    database: mysql
spec:
  minReadySeconds: 3
  replicas: 1
  selector:
    matchLabels:
      database: mysql
  strategy: 
    maxSurge: 25%
    maxUnavailable: 25%
  template:
    metadata:
      labels:
        database: mysql
    spec:
      containers: 
        - image: library/redis:5.0-alpine
          name: redis-db
          ports:
            - containerPort: 6379
              protocol: TCP