---
apiVersion: v1
kind: Deployment
metadata:
  name: saleor-db
  labels: 
    database: mysql
spec:
  minReadySeconds: 3
  replicas: 1
  selector:
    matchLabels:
      database: mysql
  strategy: 
    maxSurge: 25%
    maxUnavailable: 25%
  template:
    metadata:
      labels:
        database: mysql
    spec:
      containers: 
        - image: shaikkhajaibrahim/saleor-dashboar:DEV
          name: mikey-container
          ports:
            - containerPort: 5432
              protocol: TCP
          command:
            - python
            - manage.py
            - runserver
            - 0.0.0.0:8000
