---
apiVersion: v1
kind: Service
metadata:
  name: mikey-svc2
spec:
  type: ClusterIP
  selector: 
    matchLabels:
      deployment: saleor
  ports:
    - targetPort: 6379
      port: 35000
      protocol: TCP