---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: mikey-ds
  labels:
    app: nginx
spec:
  minReadySeconds: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: mikey-dspod
      labels:
        app: nginx
    spec:
      containers:
        - image: telegraf:1.25
          ports:
            - containerPort: 8086
              protocol: TCP
      